parameters:

services:
    azine_mailgun.service:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunService
        arguments: 
          managerRegistry:      "@doctrine"

    azine.email.text.wrap.filter:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunlTwigExtension 
        public: false
        tags:
            - { name: twig.extension }
        
          