parameters:

services:
    azine_mailgun.service:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunService
        arguments: ["@doctrine"]

    azine.mailgun.webhooks.bundle.twig.extension:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunTwigExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
