parameters:

services:
    azine_mailgun.service:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunService
        arguments: 
          entityManager:      "@doctrine.orm.entity_manager"
