mailgunevent_list:
    path:  /mailgun/events/{page}/{pageSize}
    defaults: { _controller: "AzineMailgunWebhooksBundle:MailgunEvent:index" }

mailgunevent_show:
    path:  /mailgun/event/{id}/show
    defaults: { _controller: "AzineMailgunWebhooksBundle:MailgunEvent:show" }

mailgunevent_delete:
    path:  /mailgun/event/delete/{eventId}
    defaults: { _controller: "AzineMailgunWebhooksBundle:MailgunEvent:delete" }

mailgunevent_delete_ajax:
    path:  /mailgun/event/delete
    defaults: { _controller: "AzineMailgunWebhooksBundle:MailgunEvent:delete" }

mailgun_overview:
    path:  /mailgun/
    defaults: { _controller: "AzineMailgunWebhooksBundle:Mailgun:overview" }
